const ingredientesGenerales = [
    {
      imgSrc: "src/assets/img/ingredientes/Pan_arriba.png",
      alt: "Pan campero arriba",
      nombre: "Pan de arriba",
      kcal: (250 * 60) / 100,
      carbs: ((50 * 60) / 100).toFixed(2) + "g",
      proteina: ((8 * 60) / 100).toFixed(2) + "g",
      grasas: ((3 * 60) / 100).toFixed(2) + "g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/tomate.png",
      alt: "Tomate",
      nombre: "Tomate",
      kcal: (18 * 50) / 100,
      carbs: ((3.9 * 50) / 100).toFixed(2) + "g",
      proteina: ((0.9 * 50) / 100).toFixed(2) + "g",
      grasas: ((0.2 * 50) / 100).toFixed(2) + "g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/huevo.png",
      alt: "Huevo",
      nombre: "Huevo",
      kcal: 155,
      carbs: "1.1g",
      proteina: "13g",
      grasas: "11g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/queso.png",
      alt: "Queso",
      nombre: "Queso",
      kcal: (402 * 20) / 100,
      carbs: ((1.3 * 20) / 100).toFixed(2) + "g",
      proteina: ((25 * 20) / 100).toFixed(2) + "g",
      grasas: ((33 * 20) / 100).toFixed(2) + "g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/bacon.png",
      alt: "Bacon",
      nombre: "Bacon",
      kcal: (541 * 40) / 100,
      carbs: ((1.4 * 40) / 100).toFixed(2) + "g",
      proteina: ((37 * 40) / 100).toFixed(2) + "g",
      grasas: ((42 * 40) / 100).toFixed(2) + "g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/lechuga.png",
      alt: "Lechuga",
      nombre: "Lechuga",
      kcal: (15 * 20) / 100,
      carbs: ((3 * 20) / 100).toFixed(2) + "g",
      proteina: ((1.2 * 20) / 100).toFixed(2) + "g",
      grasas: ((0.2 * 20) / 100).toFixed(2) + "g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/pollo.png",
      alt: "Pollo",
      nombre: "Pollo",
      kcal: 165,
      carbs: "0g",
      proteina: "31g",
      grasas: "3.6g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/pan_abajo.png",
      alt: "Pan campero abajo",
      nombre: "Pan de abajo",
      kcal: (250 * 60) / 100,
      carbs: ((50 * 60) / 100).toFixed(2) + "g",
      proteina: ((8 * 60) / 100).toFixed(2) + "g",
      grasas: ((3 * 60) / 100).toFixed(2) + "g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/cebolla.png",
      alt: "Cebolla",
      nombre: "Cebolla",
      kcal: 40,
      carbs: "9g",
      proteina: "1g",
      grasas: "0.1g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/cheddar.png",
      alt: "Cheddar vegano",
      nombre: "Cheddar vegano",
      kcal: 403,
      carbs: "1.3g",
      proteina: "25g",
      grasas: "33g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/falafel.png",
      alt: "Falafel",
      nombre: "Falafel",
      kcal: 330,
      carbs: "31g",
      proteina: "13g",
      grasas: "17g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/jamon.png",
      alt: "Jamón",
      nombre: "Jamón",
      kcal: 160,
      carbs: "0g",
      proteina: "31g",
      grasas: "4g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/cebolla_plancha.png",
      alt: "Cebolla a la plancha",
      nombre: "Cebolla a la plancha",
      kcal: 50,
      carbs: "11g",
      proteina: "1g",
      grasas: "0.2g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/pan_abajo_rustico.png",
      alt: "Pan abajo rústico",
      nombre: "Pan abajo rústico",
      kcal: 200,
      carbs: "45g",
      proteina: "6g",
      grasas: "2g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/pan_arriba_rustico.png",
      alt: "Pan arriba rústico",
      nombre: "Pan arriba rústico",
      kcal: 200,
      carbs: "45g",
      proteina: "6g",
      grasas: "2g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/pimiento.png",
      alt: "Pimiento",
      nombre: "Pimiento",
      kcal: 20,
      carbs: "4g",
      proteina: "0.9g",
      grasas: "0.2g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/polloasado.png",
      alt: "Pollo asado",
      nombre: "Pollo asado",
      kcal: 190,
      carbs: "0g",
      proteina: "30g",
      grasas: "8g",
    },
    {
      imgSrc: "src/assets/img/ingredientes/tortilla.png",
      alt: "Tortilla",
      nombre: "Tortilla",
      kcal: 210,
      carbs: "1g",
      proteina: "15g",
      grasas: "16g",
    },
  ].map((ingrediente, index) => ({
    id: index + 1,
    ...ingrediente,
  }));
  
  export default ingredientesGenerales;